// <auto-generated />
using System;
using MMWebAPI.Infrastructure.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MMWebAPI.Infrastructure.Repository.Migrations
{
    [DbContext(typeof(MMContext))]
    [Migration("20190502140145_teste")]
    partial class teste
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MMWebAPI.Domain.Models.FinancialTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("GroupId");

                    b.Property<string>("Title");

                    b.Property<DateTime>("TransactionDate");

                    b.Property<double>("Value");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("FinancialTransaction");
                });

            modelBuilder.Entity("MMWebAPI.Domain.Models.FinancialTransactionGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("FinancialTransactionGroup");
                });

            modelBuilder.Entity("MMWebAPI.Domain.Models.FinancialTransaction", b =>
                {
                    b.HasOne("MMWebAPI.Domain.Models.FinancialTransactionGroup", "Group")
                        .WithMany("FinancialTransactions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
